### ISSUE TITLE
[Feature] Add Ability to Not Include campaign_suppression_list_history Table

### ISSUE THREAD

**Issue by awpharr** [fivetran/dbt_iterable#19]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Describe the Feature

Right now you are not able to disable using the campaign_suppression_list_history like you are with some other tables via the variables section of the project.yml file. One of our customers (we use Powered by Fivetran) does not have this table as one of their source Iterable tables, and it would be good to have models that use that table either disabled or disregard that table if it doesn't exist.

### Are you interested in contributing this feature?

- [ ] Yes.
- [ ] Yes, but I will need assistance and will schedule time during your [office hours](https://calendly.com/fivetran-solutions-team/fivetran-solutions-team-office-hours) for guidance.
- [X] No.

**Comment by fivetran-joemarkiewicz** [comment]
Hi @awpharr thanks so much for opening this feature request.

I think this is a great enhancement to our package and we will plan to integrate this update in the package. We will most likely pick this up in our upcoming sprint (starting 11/16).
