### ISSUE TITLE
[Feature] Remove need for events replication

### ISSUE THREAD

**Issue by lfvarela** [fivetran/dbt_iterable#24]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Describe the Feature

My team decided to stop replicating Iterable event data given it's high volume and that most of the data is available elsewhere. Doing this broke some of the models in this package.

I think there are two options:

1) Support disabling models / fields that depend on events data. Judging by the codebase - this might make the package significantly less useful to the point this is not worth doing.

2) Support disabling the replication of _custom events_. This would significantly reduce our replication volume but still make use of Iterable event data which is the data that I believe is relevant for many of the models. I might be wrong here though. This would require changes from the Fivetran engineering team.

### Are you interested in contributing this feature?

- [ ] Yes.
- [ ] Yes, but I will need assistance and will schedule time during your [office hours](https://calendly.com/fivetran-solutions-team/fivetran-solutions-team-office-hours) for guidance.
- [X] No.

**Comment by fivetran-catfritz** [comment]
Hi @lfvarela! Thank you for submitting this issue. 

For option 2, this would fall outside of what my team handles, however it looks like another customer has also requested something similar in [this feature request.](https://support.fivetran.com/hc/en-us/community/posts/8176096691479-Connector-Improvement-Enhancement-Ability-to-filter-out-Iterable-Data-when-dataType-customEvent) I would suggest to comment in that thread to show your interest, which will also give you a chance to interact with a PM. 

In the meantime, our team will investigate option 1!

**Comment by fivetran-joemarkiewicz** [comment]
Hi @lfvarela thanks for opening this issue and for stirring up some great conversations amongst our team with your suggestion with Option 1.

After much deliberation, we found that moving forward with Option 1 would result in the primary use case of this package being turned off. The event data with Iterable is key and we would not want to disable this feature from the package as it would not provide analytical value if removed.

I do understand your point with needing to trim the table as the replication volume is too high. I do believe if we are able to address your concern within the connector, then you will be able to get the most value from this package. I highly encourage following @fivetran-catfritz suggestion to open a FR for our PMs to get eyes on your request and work with you to understand your suggestion.

Based on the above, I will close this issue and will mark as `wontfix` as there is not an update on the package side that we will move forward with.
