### ISSUE TITLE
int_iterable__list_user_unnest takes forever

### ISSUE THREAD

**Issue by nbenezri** [fivetran/dbt_iterable#26]
Doing `dbt run` on iterable takes a lot of time.
As you can see it takes 1 hour.
The destination is Redshift.

```
ESC[0m10:42:59  130 of 175 OK created table model cdp_int_iterable.int_iterable__list_user_unnest  [ESC[32mSELECTESC[0m in 3670.60s]
```

**Comment by fivetran-joemarkiewicz** [comment]
Hi @nbenezri thanks for sharing! I am aware that the unnesting functionality within Redshift has historically not been the most elegant. All other warehouses have a built in function to unnest arrays in data; however, Redshift does not which requires us to take the approach seen in the [int_iterable__list_user_unnest](https://github.com/fivetran/dbt_iterable/blob/2fc2e7549fd84ca9ba176d2d31d0e5541f0d9fc3/models/intermediate/int_iterable__list_user_unnest.sql#L16) model where there are Redshift specific code blocks. 

That being said, I would be curious to see if anyone else in the community has found a better and more performant option to unnest arrays using Redshift. While I go investigating some more, I would be curious to understand what the volume of data you currently have in your `user_history` source table. Additionally, do are you aware of any records that have more than a couple thousand items in the array found in the `email_list_ids` column within the user_history source table?

**Comment by nbenezri** [comment]
```
select count(*), max(REGEXP_COUNT(email_list_ids,'[,]')) from user_history;
  count  | max
---------+-----
 9717871 |  18
```

the explain says it goes over 1b records

**Comment by nbenezri** [comment]
What about https://docs.aws.amazon.com/redshift/latest/dg/query-super.html 
Also the super object.

Are any of those handy?

**Comment by fivetran-joemarkiewicz** [comment]
Thanks for sharing @nbenezri! My team is going to look into this some more this sprint and see if we find any reasonable workaround that could work for Redshift users to help with the performance.

In the meantime, if you are able to try anything and see success, let me know!

**Comment by nbenezri** [comment]
From what I saw CTE doesn't work and you have to create a table for unnest functionality.
It will look like this:

```
dkall=# create table dbe.test as select json_parse(email_list_ids) id from user_history limit 1;
SELECT
dkall=# select * from dbe.test;
            id
---------------------------
 [1669701,1728915,1748922]
(1 row)

dkall=# select id2 from dbe.test as ids, ids.id id2;
   id2
---------
 1669701
 1728915
 1748922
(3 rows)
```

**Comment by fivetran-joemarkiewicz** [comment]
Thanks for sharing this @nbenezri this is interesting as we have been able to perform the unnest functionality in Redshift within a CTE. However, I have never attempted it on a large dataset. That being said it may be worth exploring breaking the Redshift unnest functionality out into an intermediate model that is materialized as a table, and then perform the unnesting from there.

Have you been able to try this with your own data? Does it reduce the time to run significantly?

**Comment by nbenezri** [comment]
sure.

compared to the 3670.60s above, my version took 20s.

```
[analytics ]$ cat a.sh
echo "start create table "$(date +"%Y-%m-%d %H:%M:%S")
echo "
drop table if exists dbe.test;
create table dbe.test
as
select  email,
        first_name,
        last_name,
        user_id,
        signup_date,
        signup_source,
        phone_number,
        updated_at,
        case when email_list_ids != '[]' then json_parse(email_list_ids)
             else null end as email_list_id
from user_history;
" | psql > /tmp/a.log

echo "start select from table "$(date +"%Y-%m-%d %H:%M:%S")
echo "
drop table if exists dbe.test_final;
create table dbe.test_final
as
select email,
        first_name,
        last_name,
        user_id,
        signup_date,
        signup_source,
        phone_number,
        updated_at,
        email_id
from dbe.test as ids,
     ids.email_list_id email_id;
" | psql >> /tmp/a.log

echo "end "$(date +"%Y-%m-%d %H:%M:%S")
[analytics ]$ ./a.sh
start create table 2023-04-10 14:54:51
start select from table 2023-04-10 14:54:57
end 2023-04-10 14:55:11
```

The table `dbe.test_final` has `50030969` rows

**Comment by fivetran-joemarkiewicz** [comment]
Thanks for sharing @nbenezri! Our team will evaluate in more detail during our next sprint.

**Comment by fivetran-jamie** [comment]
FYI working on this now! i'll ping you @nbenezri with a working branch to test out later if you've got time

**Comment by fivetran-jamie** [comment]
@nbenezri your code was super helpful and i completely ripped it off thank you 😎  i also added some incremental materialization logic to see if we can optimize this further

could you test the below branch out? our own data is pretty limited so incredibly curious how/if this changed things 👀
```yml
# packages.yml
packages:
  - git: https://github.com/fivetran/dbt_iterable.git
    revision: feature/optimize-list-unnesting
```

**Comment by nbenezri** [comment]
Our dev is light. I will be able to test it only on prod (when it will reach the main branch)

**Comment by fivetran-jamie** [comment]
gotcha -- rolling it out right now and i'll ping you here when the changes are live on main/dbt hub!

**Comment by fivetran-jamie** [comment]
changes are live in [v0.7.0](https://github.com/fivetran/dbt_iterable/releases/tag/v0.7.0)! @nbenezri

**Comment by nbenezri** [comment]
will test it out and report back in a few weeks.
thanks!!

**Comment by fivetran-jamie** [comment]
closing this issue for now but please reopen if the performance problem persists!
