### ISSUE TITLE
[Bug] int_iterable__list_user_unnest inconsistency between warehouses

### ISSUE THREAD

**Issue by fivetran-catfritz** [fivetran/dbt_iterable#31]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the issue

Depending on the warehouse, different results are produced for model `int_iterable__list_user_unnest` when using seed data. For example, in Bigquery and Snowflake, `email_list_ids` with an empty string are not included, while they are in Postgres and Databricks. This results in Postgres and Databricks having more rows in this intermediate model (see screenshots). This is most likely due to the different sets of rules required for each warehouse. 

![Screenshot 2023-06-23 at 2 24 41 PM](https://github.com/fivetran/dbt_iterable/assets/111930712/65351d66-71fe-4672-bcfd-35fb11c2335c)
![Screenshot 2023-06-23 at 2 20 48 PM](https://github.com/fivetran/dbt_iterable/assets/111930712/fa2140ff-8a7e-4f50-b715-8aacf19e9c74)

### Expected behavior

1. Decide whether or not to include rows with empty `email_list_ids`.
2. Implement decision across all warehouses so they to produce the same outputs.

### dbt Project configurations

using seed data

### Package versions

8.0

### What database are you using dbt with?

postgres, redshift, snowflake, bigquery, databricks

### dbt Version

1.5+

### Are you willing to open a PR to help address this issue?

- [X] Yes.
- [ ] Yes, but I will need assistance and will schedule time during our [office hours](https://calendly.com/fivetran-solutions-team/fivetran-solutions-team-office-hours) for guidance
- [ ] No.

**Comment by fivetran-joemarkiewicz** [comment]
@fivetran-catfritz I wonder if it is this line that is causing the issue you are seeing.

https://github.com/fivetran/dbt_iterable/blob/7863ee136350119cdc725875aa3becc2762f3ecb/models/intermediate/int_iterable__list_user_unnest.sql#L73

It may not be the incremental strategy but instead how the different databases handle empty lists. Do you see this same error across the databases when doing full refreshes? Or is this **only** seen on incremental runs?
