### ISSUE TITLE
[Bug] iterable__user_campaign duplicate test failing if users have updated their name

### ISSUE THREAD

**Issue by brendangeisler** [fivetran/dbt_iterable#32]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the issue

Hello!

I recently installed the package and am receiving a failure on the `iterable__user_campaign` object. `Failure in test dbt_utils_unique_combination_of_columns_iterable__user_campaign_user_email__campaign_id__experiment_id (models/iterable.yml)`

I believe it happens when a user changes their name.  the `iterable__events`  object references the `int_iterable__latest_user` object - which correctly returns 1 user per email.  However, since events is incremental, there are records in the events table with both of the user's names (before and after they've updated it).  On its own, events looks correct, but since the `iterable__user_campaign` object groups with user_full_name in it, I am seeing duplicate records (especially for instances where campaign_id and experiment_id are null.

Let me know what you think.

Thanks,
Brendan

### Relevant error log or model output

```shell
`Failure in test dbt_utils_unique_combination_of_columns_iterable__user_campaign_user_email__campaign_id__experiment_id (models/iterable.yml)`
```

### Expected behavior

Either the test should include user name as part of the key or user_full_name should be joined after the grouping.

### dbt Project configurations

    iterable__using_campaign_label_history: false   

### Package versions

 - package: fivetran/iterable
    version: 0.8.0

### What database are you using dbt with?

snowflake

### dbt Version

1.3

### Are you willing to open a PR to help address this issue?

- [ ] Yes.
- [ ] Yes, but I will need assistance and will schedule time during our [office hours](https://calendly.com/fivetran-solutions-team/fivetran-solutions-team-office-hours) for guidance
- [ ] No.

**Comment by fivetran-joemarkiewicz** [comment]
Hi @brendangeisler thanks for opening this issue! 

This is actually something we identified as a behavior of the `delete_insert` incremental strategy within dbt. We came across this same behavior when working on an update to our Fivetran Log dbt package. Here is a callout we have drafted and was curious what your thoughts were

> Some of the end models in this package are materialized incrementally. We have chosen insert_overwrite as the default strategy for BigQuery and Databricks databases, as it is only available for these dbt adapters. For Snowflake, Redshift, and Postgres databases, we have chosen delete+insert as the default strategy.
> 
> insert_overwrite is our preferred incremental strategy because it will be able to properly handle updates to records that exist outside the immediate incremental window. That is, because it leverages partitions, insert_overwrite will appropriately update existing rows that have been changed upstream instead of inserting duplicates of them--all without requiring a full table scan.
> 
> delete+insert is our second-choice as it resembles insert_overwrite but lacks partitions. This strategy works most of the time and appropriately handles incremental loads that do not contain changes to past records. However, if a past record has been updated and is outside of the incremental window, delete+insert will insert a duplicate record. 😱
> 
> Because of this, we highly recommend that Snowflake, Redshift, and Postgres users periodically run a --full-refresh to ensure a high level of data quality and remove any possible duplicates.

Would you also be able to confirm that running a `--full-refresh` does in fact resolve the error you are seeing? If that is the case, then I would recommend periodically running a full refresh on the table to be sure the incremental strategy is able to capture updates like the one you are describing. Unfortunately, this is something that the `insert_overwrite` strategy is able to capture automatically, but it is not available within Snowflake, Redshift, or Postgres 😢. 

Let me know your thoughts!

**Comment by fivetran-joemarkiewicz** [comment]
@brendangeisler I have just added the description above to the README for the package. The idea is that this will allow users who are not using BigQuery or Databricks to understand the limitation and the need for periodic full refreshes of these tables to capture updates outside of the incremental window. 

As such, I will close this issue. Please feel free to add any more thoughts to this thread if you have concerns. Thanks!

**Comment by brendangeisler** [comment]
Hi @fivetran-joemarkiewicz - Somehow missed your original response.  Thanks for the details.  A full refresh did allow the model tests to pass.  I'm still not sure I'm going to add a refresh step to our regular deployments.  I'll do some more brainstorming on my side.  Thanks again for your help.
