### ISSUE TITLE
[Bug] Fan-out on `iterable__events` due to primary key schema updates with `_fivetran_user_id` on `event_extension` and `event` 

### ISSUE THREAD

**Issue by fivetran-avinash** [fivetran/dbt_iterable#38]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the issue

A customer reported that they were seeing nearly triple the number of event records than expected in the `iterable__events` model than were coming in from the `events` source in their data. Further investigation revealed that `iterable__events` was bringing in duplicate event ids. That is unexpected behavior as `event_id` has a test on uniqueness in this model. 

Further investigation on the customer's data led us to the join on the `event_extension` causing a fanout of records. This brought us back to [the recent schema updates on Iterable,](https://docs.google.com/presentation/d/1a3EbweWbiu4xNCaGBQV62FLuva9W7PndDmvyITaxtAw/edit#slide=id.g219e65a8a00_0_0) where the `_fivetran_user_id` was being brought into both `event` and `event_extension` as the primary id. Those are not part of the join at the moment, so the model is producing erroneous duplicative records on the `event_id` grain.

Two issues need to be fixed.
1) `_fivetran_user_id` needs to be brought into `event` and `event_extension` in the source model and tests need to be adjusted. That is part of the new schema update issue in `iterable_source`; [click here for more details.](https://github.com/fivetran/dbt_iterable_source/issues/27)
2) The join needs to be adjusted in `iterable__events` to account for `_fivetran_user_id` and our tests need to be modified to account for the new logic, which will be the focus of this particular issue. 

### Expected behavior

A unique event key should be returned for each event_id in `iterable__events`. 

### dbt Project configurations

the yml file:

> name: 'efgy_dbt'
> version: '1.0.0'
> config-version: 2
> 
> ### This setting configures which "profile" dbt uses for this project.
> profile: 'efgy_dbt'
> 
> ### These configurations specify where dbt should look for different types of files.
> ### The `model-paths` config, for example, states that models in this project can be
> ### found in the "models/" directory. You probably won't need to change these!
> model-paths: ["models"]
> analysis-paths: ["analyses"]
> test-paths: ["tests"]
> seed-paths: ["seeds"]
> macro-paths: ["macros"]
> snapshot-paths: ["snapshots"]
> 
> clean-targets:         # directories to be removed by `dbt clean`
>   - "target"
>   - "dbt_packages"
> 
> vars:
>   efgy_schemas: [_base,_salesforce, _iterable]
>   iterable_database: GAPYEAR 
>   iterable_schema: FIVETRAN_ITERABLE

> 
> 
> ### Configuring models 
> ### Full documentation: https://docs.getdbt.com/docs/configuring-models
> 
> ### In this example config, we tell dbt to build all models in the salesforce/
> ### directory as views. These settings can be overridden in the individual model
> ### files using the `{{ config(...) }}` macro.
> models:
>   efgy_dbt:
>     # Config indicated by + and applies to all files under models/salesforce/    
>     salesforce:
>       +enabled: true
>       +materialized: view
>       +schema: salesforce
>     base:
>       +enabled: true
>       +materialized: table
>       +schema: base
>     derived:
>       +enabled: true
>       +materialized: table
> 
> on-run-end:
>     - "{{ grant_permissions_on_schemas() }}"

### Package versions

> packages:
>   - package: dbt-labs/dbt_utils
>     version: [">=1.0.0"]
>   - package: fivetran/salesforce_formula_utils
>     version: [">=0.8.0", "<0.9.0"]
>   - package: fivetran/iterable
>     version: [">=0.8.0", "<0.9.0"]

### What database are you using dbt with?

other (mention it in "Additional Context")

### dbt Version

The DBT version they are using is 1.6.4.

Customer is using transformations. 

### Are you willing to open a PR to help address this issue?

- [X] Yes.
- [ ] Yes, but I will need assistance and will schedule time during our [office hours](https://calendly.com/fivetran-solutions-team/fivetran-solutions-team-office-hours) for guidance
- [ ] No.

**Comment by fivetran-reneeli** [comment]
This has been addressed in the latest release.
