### ISSUE TITLE
iterable__user_unsubscriptions - bad updated_date

### ISSUE THREAD

**Issue by rick1290** [fivetran/dbt_iterable#41]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the issue

Note on iterable dbt package.

iterable__user_unsubscriptions: 

updated_at Timestamp of when the user unsubscribed from the channel or message type

The above definition for that column is wrong in that table - it seems that the update_at - is the last date of any unsubscription - not the actual date of the unsubscription. So if I unsubsubcribed from X 2 years ago - and the I unsubscribe from Y yesterday. All those rows will be updated to the yesterday date. Its also mixing subscriptions to lists vs. channels/messagetypes when it comes to dates. Makes this table difficult to work with. 

https://fivetran.github.io/dbt_iterable/#!/model/model.iterable.iterable__user_unsubscriptions

### Relevant error log or model output

```shell
Note on iterable dbt package.

iterable__user_unsubscriptions: 

updated_at Timestamp of when the user unsubscribed from the channel or message type

The above definition for that column is wrong in that table - it seems that the update_at - is the last date of any unsubscription - not the actual date of the unsubscription. So if I unsubsubcribed from X 2 years ago - and the I unsubscribe from Y yesterday. All those rows will be updated to the yesterday date. Its also mixing subscriptions to lists vs. channels/messagetypes when it comes to dates. Makes this table difficult to work with. 

https://fivetran.github.io/dbt_iterable/#!/model/model.iterable.iterable__user_unsubscriptions
```

### Expected behavior

The `updated_date` should be the date of the actual unsubscription date

### dbt Project configurations

Default package

### Package versions

  - package: fivetran/iterable
    version: 0.10.0

### What database are you using dbt with?

bigquery

### dbt Version

Most recent

### Additional Context

I love these iterable packages - keep them coming :) 

These queries are difficult to write so these come in handy. I'd love to see this table fixed tho - this one is quite important to us:) 

### Are you willing to open a PR to help address this issue?

- [ ] Yes.
- [X] Yes, but I will need assistance and will schedule time during our [office hours](https://calendly.com/fivetran-solutions-team/fivetran-solutions-team-office-hours) for guidance
- [ ] No.

**Comment by fivetran-catfritz** [comment]
Hi @rick1290 thank you for opening this issue. We will review this in the next day or so and let you know if we have any questions.

**Comment by rick1290** [comment]
Thanks! @fivetran-catfritz Will stay posted :)

**Comment by fivetran-catfritz** [comment]
Hi @rick1290 I am reviewing this and have a couple questions. Could you confirm if you have the source table `USER_UNSUBSCRIBED_CHANNEL` with the column `_fivetran_id`? There was a schema change on August 10, 2023, so it would be helpful to know if you're on the [old schema](https://docs.google.com/presentation/d/1uxDsylyzrajYNAz-zJJBat-DxZbLPlueA3KM7mGBrQY/edit#slide=id.g22957ad5d71_1_0) or the [new schema](https://docs.google.com/presentation/d/1a3EbweWbiu4xNCaGBQV62FLuva9W7PndDmvyITaxtAw/edit#slide=id.g219e65a8a00_0_0). 

Also I see that you are on v0.10.0 of the package. I don't think upgrading to the current version v0.11.0 will necessarily solve this particular issue, but I'm also wondering if you have tried it out/had issues with it?

**Comment by rick1290** [comment]
@fivetran-catfritz I'm on the old schema

Agreed - don't think upgrading as well will help. I've been upgrading over time and havn't seen any changes. I can try when I get some time next week.

**Comment by fivetran-jamie** [comment]
Hi there @rick1290 -- this `latest_batch_index` [window](https://github.com/fivetran/dbt_iterable_source/blob/main/models/stg_iterable__user_unsubscribed_channel.sql#L36) function is likely the culprit, as it will return the latest unsubscribed timestamp for each user across all channels/message types, and we use it to filter out records [here](https://github.com/fivetran/dbt_iterable/blob/main/models/iterable__user_unsubscriptions.sql#L11). 

I believe adding `channel_id` or `message_type_id` to the partition clause of the window functions would resolve the issue, mostly. This would then return the latest unsubscription timestamp per user per channel/message type. I am wondering if it makes sense to return the latest timestamp (in case a user has unsubscribed, re-subscribed, and unsubscribed again from the same channel) or instead return the first unsubscription timestamp?

As for your later point 
> Its also mixing subscriptions to lists vs. channels/messagetypes when it comes to dates. Makes this table difficult to work with

Would you mind clarifying a bit here?

**Comment by rick1290** [comment]
@fivetran-jamie Great!

`latest unsubscription timestamp per user per channel/message type`

The above is the logic we want for this.

In regards to clarifying - we just want to make sure that the timestamps are for channel/message types - and not when a user drops from a list. 

Really glad you are working on a fix for this!

**Comment by fivetran-jamie** [comment]
Gotcha cool! Would you be willing to test out a working branch when we have a fix drafted?

**Comment by rick1290** [comment]
Yep :)

**Comment by rick1290** [comment]
@fivetran-jamie Any update or progress on this issue :) 

Thanks1

**Comment by fivetran-avinash** [comment]
Hi @rick1290 ! I've currently taken on the work on this bug from @fivetran-jamie  and am hoping to have a fix ready by the end of this sprint.

I've deployed the proposed changes in the `dbt_iterable_source` package that should bring in the latest unsubscription behavior for an email based on channel_id and message_type_id, and should bring in the latest unsubscribes on both the message_type and channel level.

You can test the changes before we go ahead and deploy them alive. Would you be able to update the `packages.yml` file in your `dbt_iterable` package to:

```
packages:  
  - git: https://github.com/fivetran/dbt_iterable_source.git
    revision: bugfix/catch-all-recent-unsubscribes 
    warn-unpinned: false

```

Then run your package and see if everything looks as proposed? This will provide the final level of validation needed for us to merge this into a new release!

Thanks for your patience.

**Comment by fivetran-avinash** [comment]
Hi @rick1290 ! This new version of `dbt_iterable_source` is now live [in our latest v0.8.1 release](https://hub.getdbt.com/fivetran/iterable_source/latest/) with the changes that should bring in all the latest unsubscribes in the `iterable__user_unsubscriptions` model. You can run `dbt deps` to pick up the latest version of the package.

Let us know if you experience any issues here!

**Comment by rick1290** [comment]
@fivetran-avinash Thanks! Do I need to run a full refresh or anything?

**Comment by rick1290** [comment]
@fivetran-avinash 

I get the following errors when I run a ful-refresh. Mind you - our data is from 2021 - so we are on legacy schema. Have the new updates been tested on the original schema? I read the breaking changes - but not sure it should be causing errors. 

Thanks!!

```
02:45:43    Database Error in model int_iterable__latest_user (models/intermediate/int_iterable__latest_user.sql)
  Unrecognized name: unique_user_key at [13:38]
  compiled Code at target/run/iterable/models/intermediate/int_iterable__latest_user.sql
02:45:43  
02:45:43
02:45:43    Database Error in model int_iterable__list_user_history (models/intermediate/int_iterable__list_user_history.sql)
  Unrecognized name: unique_user_key at [23:47]
  compiled Code at target/run/iterable/models/intermediate/int_iterable__list_user_history.sql
02:45:43  
02:45:43
02:45:43    Runtime Error in model iterable__user_unsubscriptions (models/iterable__user_unsubscriptions.sql)
  404 Not found: Table tsn-marketing-operations:dbt_models_stg_iterable.stg_iterable__user_unsubscribed_channel was not found in location US; reason: notFound, message: Not found: Table tsn-marketing-operations:dbt_models_stg_iterable.stg_iterable__user_unsubscribed_channel was not found in location US
```

**Comment by rick1290** [comment]
Just reverted back to v10 and its working. Would love to see how I can get v11 working with these awesome new changes :)

**Comment by rick1290** [comment]
Morning @fivetran-avinash Please see the below:

```
15:52:29 Running with dbt=1.6.14
15:52:30 Installing fivetran/iterable
15:52:31 Installed from version 0.11.0
15:52:31 Up to date!
```

**Comment by fivetran-joemarkiewicz** [comment]
Hey @rick1290, @fivetran-avinash is OOO for the rest of the week, so I'll jump in to help for the time being.

It looks like the only contents we see there are for the `fivetran/iterable` dbt package, but not the `fivetran/iterable_source` package (where Avinash's changes were made). 🤔 

Would you be able to share the contents of your `packages.yml`?

**Comment by rick1290** [comment]
@fivetran-joemarkiewicz See below. I believe the fivetran iterable source is automatically included in the iterable package.

Let me know if you need anything else! :) 

`
# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'x'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'default'

# These configurations specify where dbt should look for different types of files.
# The `source-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
    - "target"
    - "dbt_packages"

tests:
  +severity: warn  # all tests


# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

# In this example config, we tell dbt to build all models in the example/ directory
# as tables. These settings can be overridden in the individual model files
# using the `{{ config(...) }}` macro.
models:
  shift_analytics_project:
      # Applies to all files under models/example/
      materialized: table
      staging:
          materialized: view
      pinterest:
          enabled: false
      pinterest_source:
          enabled: false
        # disable both linkedin ads models if not using linkedin ads
      linkedin:
          enabled: false
      linkedin_source:
          enabled: false
        # disable both twitter ads models if not using twitter ads
      twitter_ads:
          enabled: false
      twitter_ads_source:
          enabled: false
      # disable both snapchat ads models if not using snapchat ads
      snapchat_ads:
          enabled: false
      snapchat_ads_source:
          enabled: false
       # disable both instagram business models if not using instagram business
      instagram_business:
          enabled: false
      instagram_business_source:
          enabled: false
      # disable both twitter organic models if not using twitter organic
      twitter_organic:
          enabled: false
      twitter_organic_source:
          enabled: false
      # disable both tiktok ads models if not using tiktok ads
      tiktok_ads:
        enabled: false
      tiktok_ads_source:
        enabled: false
      google_ads:
        +schema: google_ads
      google_ads_source:
        +schema: google_ads_source
      facebook_ads:
        +schema: facebook_ads
      facebook_ads_source:
        +schema: facebook_ads_source
      facebook_ads_creative_history:
        +schema: facebook_ads
      microsoft_ads:
        +schema: microsoft_ads
      microsoft_ads_source:
        +schema: microsoft_ads_source
      ad_reporting:
        +schema: ad_reporting

      
vars:
    facebook_ads_schema: fb_ads
    google_ads_schema: google_ads_new_api
    microsoft_ads_schema: bingads
    ad_reporting__pinterest_ads_enabled: False
    ad_reporting__amazon_ads_enabled: False
    ad_reporting__linkedin_ads_enabled: False
    ad_reporting__twitter_ads_enabled: False
    ad_reporting__snapchat_ads_enabled: False
    ad_reporting__tiktok_ads_enabled: False
    social_media_rollup__twitter_enabled: False
    social_media_rollup__linkedin_enabled: False
    ad_reporting__apple_search_ads_enabled: False
    ad_reporting__reddit_ads_enabled: False
    amplitude_schema: amplitude_new
    amplitude__date_range_start: '2020-01-01' # your start date here
    amplitude__date_range_end: '2023-12-31' # your end date here
    event_properties_to_pivot: ['pns','pagePath', 'title','url', 'nid','utmSource', 'attribution_id','email', 'position', 'rating','comment', 'status', 'orderid']
    user_properties_to_pivot: ['utm_source','utm_medium', 'utm_campaign', 'utm_content', 'isPractitioner', 'learningPreference', 'goals']
    id-columns: ('anonymous_id', 'user_id', 'email', 'context_traits_email', 'amplitude_id')`

**Comment by fivetran-joemarkiewicz** [comment]
Hey @rick1290 it looks like you shared the contents of the `dbt_project.yml`. Would you be able to share the `packages.yml` contents? Additionally, do you by chance have a `package-lock.yml` in your project? You are correct that the source package should be installed automatically, but it doesn't seem to be the case as we don't see the source installation in your [above response](https://github.com/fivetran/dbt_iterable/issues/41#issuecomment-2137748915).

**Comment by rick1290** [comment]
@fivetran-joemarkiewicz Oops.

`packages:

  - package: fivetran/iterable
    version: 0.11.0

  - package: fivetran/ad_reporting
    version: [">=1.6.0", "<1.7.0"] # we recommend using ranges to capture non-breaking changes automatically

  - package: fivetran/social_media_reporting
    version: 0.2.0
    
  - package: fivetran/youtube_analytics
    version: 0.3.0

  - package: narratorai/activity_schema
    version: 0.1.0

  - package: dbt-labs/audit_helper
    version: 0.9.0

  - package: mjirv/dbt_product_analytics
    version: [">=0.1.0"]

  - package: fivetran/amplitude
    version: [">=0.4.0", "<0.5.0"] # we recommend using ranges to capture non-breaking changes automatically`

**Comment by rick1290** [comment]
@fivetran-joemarkiewicz No lock.yml in the project

Any other ideas?

**Comment by fivetran-joemarkiewicz** [comment]
Thanks @rick1290, and just to confirm you do not see `fivetran/iterable_source` anywhere in your dbt deps log?

Also, when you full refreshed, did you run `dbt run -s +iterable --full-refresh`? It doesn't seem like the upstream changes were captured in the run where you see the error. I can mainly see this due to the error message that `stg_iterable__user_unsubscribed_channel` does not exist. This is a renamed model from the [v0.8.0 dbt_iterable_source](https://github.com/fivetran/dbt_iterable_source/releases/tag/v0.8.0) release. On a full refresh (while also running the upstream models) this error shouldn't occur. 

One last attempt here would be to try the following steps:
- run `dbt clean`
- run `dbt deps` (confirm iterable_source v0.8.1 is installed)
- run `dbt run -s +iterable --full-refresh`

Ideally after these steps you should see success. Let me know if this works!

**Comment by rick1290** [comment]
@fivetran-avinash @fivetran-joemarkiewicz 

The above worked - thanks!

That said - take a look at the following screenshot. I'm still seeing the same original bug on the new tables. The updated_at date is being attached to ALL channels and messages. The updated_at date should be the date the user unsubscribed from the channel or message_type. Should be a unique date_time for each channel if they were unsubscribed individually.


<img width="1031" alt="Screenshot 2024-06-05 at 3 28 16 PM" src="https://github.com/fivetran/dbt_iterable/assets/92341360/be1db12f-fe45-462e-8af9-235660bc8df4">

**Comment by rick1290** [comment]
Below is an example of a user actually 'subscribing' to the channel/type and non unsubscribing on 5-10-24 but the channel is included in the unsubscribe table along with the date subscribed.

<img width="851" alt="Screenshot 2024-06-05 at 3 55 02 PM" src="https://github.com/fivetran/dbt_iterable/assets/92341360/828f308a-6a17-4fe9-b2f3-f37672c8cf59">

I'm wondering if we need another column in here - that is boolean - that lets us know if they are current unsubscribed from the message_type_name? Any other ideas?

**Comment by rick1290** [comment]
<img width="651" alt="Screenshot 2024-06-05 at 4 02 28 PM" src="https://github.com/fivetran/dbt_iterable/assets/92341360/5ba20185-8068-433f-b633-b999d1af91b7">

An example of a user who unsubscribed 2-27-24 then resubscribed on 4-10-24. The 6-05-24 was attached to no subscription action. 

I'm thinking subscribe may be getting mixed in here somehow - and something else I can't figure out for the 6-05 date stamp.

**Comment by fivetran-avinash** [comment]
Hi @rick1290 , I'm wondering if your run is still utilizing the old version of the `iterable_source` package. If this data you provided is all reflective of one user, the new partitions should be creating unique indices based off of the `email/channel_id` and `email/message_type_id` mode  and taking those unique `updated_at` times. 

Are you able to view the compiled code on the new tables? It should be in [your target/compiled folder](https://docs.getdbt.com/reference/commands/compile). Can you check and see if the new compiled code for `stg_iterable__user_unsub_message_type` and `stg_iterable__user_unsubscribed_channel` matches the new partition logic on [the v0.8.1 version](https://github.com/fivetran/dbt_iterable_source/pull/30/files#diff-1731e13472ef8fb059286942e999ef57146a5366530e2052de00b7d279627e21)?

**Comment by fivetran-avinash** [comment]
> Below is an example of a user actually 'subscribing' to the channel/type and not unsubscribing on 5-10-24 but the channel is included in the unsubscribe table along with the date subscribed.
> 
> <img alt="Screenshot 2024-06-05 at 3 55 02 PM" width="851" src="https://private-user-images.githubusercontent.com/92341360/337041274-828f308a-6a17-4fe9-b2f3-f37672c8cf59.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc2Mjg1NDEsIm5iZiI6MTcxNzYyODI0MSwicGF0aCI6Ii85MjM0MTM2MC8zMzcwNDEyNzQtODI4ZjMwOGEtNmExNy00ZmU5LWIyZjMtZjM3NjcyYzhjZjU5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA1VDIyNTcyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIxOWVmZGNkMmFlMjNiZjc2NWM1YWMxZWNiNGQ5MGM3Y2ViOWZmZWZhY2UxODUwMDU2OWM3NzAxYzVlMWMyZTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.6ztQAQ59hnI3AgvHWpACSRXYSUBgPq6SwFuiqaEm1Vg">
> I'm wondering if we need another column in here - that is boolean - that lets us know if they are current unsubscribed from the message_type_name? Any other ideas?

Interesting findings @rick1290 ! These last two messages feels like a separate issue though--why is any subscription data appearing in the unsubscribe table? That feels like a connector issue. This is worth [ filing a support ticket with our Fivetran team](https://support.fivetran.com/hc/en-us)) to see why subscription data is appearing at all.

**Comment by rick1290** [comment]
@fivetran-avinash 

> Hi @rick1290 , I'm wondering if your run is still utilizing the old version of the `iterable_source` package. If this data you provided is all reflective of one user, the new partitions should be creating unique indices based off of the `email/channel_id` and `email/message_type_id` mode and taking those unique `updated_at` times.
> 
> Are you able to view the compiled code on the new tables? It should be in [your target/compiled folder](https://docs.getdbt.com/reference/commands/compile). Can you check and see if the new compiled code for `stg_iterable__user_unsub_message_type` and `stg_iterable__user_unsubscribed_channel` matches the new partition logic on [the v0.8.1 version](https://github.com/fivetran/dbt_iterable_source/pull/30/files#diff-1731e13472ef8fb059286942e999ef57146a5366530e2052de00b7d279627e21)?

It matches - confirmed.

**Comment by rick1290** [comment]
> > Below is an example of a user actually 'subscribing' to the channel/type and not unsubscribing on 5-10-24 but the channel is included in the unsubscribe table along with the date subscribed.
> > <img alt="Screenshot 2024-06-05 at 3 55 02 PM" width="851" src="https://private-user-images.githubusercontent.com/92341360/337041274-828f308a-6a17-4fe9-b2f3-f37672c8cf59.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc2Mjg1NDEsIm5iZiI6MTcxNzYyODI0MSwicGF0aCI6Ii85MjM0MTM2MC8zMzcwNDEyNzQtODI4ZjMwOGEtNmExNy00ZmU5LWIyZjMtZjM3NjcyYzhjZjU5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA1VDIyNTcyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIxOWVmZGNkMmFlMjNiZjc2NWM1YWMxZWNiNGQ5MGM3Y2ViOWZmZWZhY2UxODUwMDU2OWM3NzAxYzVlMWMyZTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.6ztQAQ59hnI3AgvHWpACSRXYSUBgPq6SwFuiqaEm1Vg">
> > I'm wondering if we need another column in here - that is boolean - that lets us know if they are current unsubscribed from the message_type_name? Any other ideas?
> 
> Interesting findings @rick1290 ! These last two messages feels like a separate issue though--why is any subscription data appearing in the unsubscribe tables? That feels like a connector issue. This is worth [ filing a support ticket with our Fivetran team](https://support.fivetran.com/hc/en-us) to see why subscription data is appearing at all.

I don't believe this is a sync issue as I initially filed a ticket which led me to filing the issue here as I believe this is tied to the underlying data models being run in this package. When I look at custom events in the iterable_event table - all those unsubscribe and subscribe events are correct. For some reason though - the subscribe event date/time is being added to the updated_at field. 

Happy to hop on a quick call to discuss this more :) I'm going to be thrilled once this use-case can be solved by the package.

**Comment by rick1290** [comment]
<img width="498" alt="Screenshot 2024-06-05 at 4 48 55 PM" src="https://github.com/fivetran/dbt_iterable/assets/92341360/2e1c2deb-7aae-4e80-97c5-18cad6ec5811">

I'm now spot checking the user_unsubscribed_channel_history table... could be a sync issue....

These dates don't make any sense :( :(

**Comment by rick1290** [comment]
<img width="575" alt="Screenshot 2024-06-05 at 5 21 06 PM" src="https://github.com/fivetran/dbt_iterable/assets/92341360/c65c156f-b974-4715-b529-0ac6d16ae505">

I was thinking maybe the new connector could solve this - but i'm not seeing any date stamps on the unsubscribe tables. Filed a ticket in the meantime - thanks for the help on this!

**Comment by fivetran-avinash** [comment]
Hi @rick1290, thanks for the thorough investigation! I believe this is still a Fivetran connector issue. The `updated_at` value is not properly processing the unsubscribe time events in the way we would expect. That is not something our data models can control for, as we expect the `updated_at` value to be consistent for the time of an unsubscribe event. 

So to summarize,

- The iterable `event` table is properly bringing in subscribe and unsubscribe events at the time they occur.
- However, the iterable `user_unsubscribed_message_type_history` and `user_unsubscribed_channel_history` tables are not getting the proper times from the `updated_at` value. 

Some examples of incorrect `updated_at` behavior in these tables in the examples you've shown above:  
- Subscribe events showing up in the unsubscribe tables
- The same `updated_at` value for an email regardless of channel or message type (Maybe it's taking the most recent event? unsure of the behavior)
- Users who unsubscribe, resubscribe, but the unsubscribe times do not capture the unsubscribe, only the resubscribe.

I'm seeing you created an additional ticket. I would relay all this information in the last few comments you provided in this thread to Fivetran support, particularly the screenshots regarding the edge cases you see. That way they can investigate what's happening in each case thoroughly. Hopefully, it's a bug, and this can be resolved internally.

If the behavior of the connector has changed for the `updated_at` values in these history models, then we can schedule a call, reopen this ticket, and take next steps.

Let me know if this all makes sense!

**Comment by rick1290** [comment]
I see - thanks everything.. .very much appreciated!!!

**Comment by rick1290** [comment]
@fivetran-avinash 

Still not progress with support on this request unfortunately. 

I thought I'd note one thing. I think it would be quite awesome if we can take event_name = 'emailUnSubscribe' and use that event to build an unsubscribe table and then compares it to the user table. Somehow I think this is the only way to get accurate unsubscribe data as the current methods are not accurate.

**Comment by fivetran-avinash** [comment]
Hi @rick1290 , good investigation on your side! It'd be interesting to see if we could incorporate this idea to create a more sustainable event model. 

Would you be able to share your data of how using the `event_name= emailUnSubscribe` would be able to fill the same role for rebuilding the  `iterable__user_unsubscriptions` model for your purpose, particularly with the additional grains on channel and message type? Also, is the proper timestamp coming through in all cases in your data?

(You can do it in the support ticket too if it's PII, but just let me know here so I can take a look!)

**Comment by rick1290** [comment]
@fivetran-avinash Yep - this would be awesome to see. 

event_name= emailUnSubscribe and emailSubscribe match our data perfectly - so it makes sense to use.

Essentially, you'd use the iterable__event table - to get emailUnSubscribe and emailSubscribe data/events.

UNEST channel_id's and message_types in additional_properties ---> which would create a new row for each email, id + unsubscribe event.

Write a rule to check if emailUnSubscribe date > emailSubscribe date for each email, id combo. This will provide accurate data on IF the user is current unsubscribed or subscribes to a channel or message type. 

You can then join this back on the channel group - and find out if they are unsubscribed channel wide.

Happy to do a workshop and discuss with you more. I've gone down a rabbit hole on this and build something for this today --- pretty raw tho - but it works.

**Comment by rick1290** [comment]
@fivetran-avinash Were you able to see the query that was created by the support team in my ticket? If you have time - would love to get your thoughts and see how it can be reflected in the dbt package to make things accurate. 

The query they provides works - but i'm still not sure its the best approach - but want to see what you think. Thanks!!
