### ISSUE TITLE
FEATURE - add support for dbt 0.20.0

### ISSUE THREAD

**Issue by justinwagg** [fivetran/dbt_iterable#5]
**Are you a Fivetran customer?** 
Yes, Justin Wagg, Data Eng, quip

**Is your feature request related to a problem? Please describe.**
 
The package currently requires dbt versions `[">=0.18.0", "<0.20.0"]`, and depends on packages which also require the same thing. 

**Describe the solution you'd like**
Add support for 0.20.0

**Describe alternatives you've considered**

**Additional context**

**Please indicate the level of urgency and business impact of this request** 

**Are you interested in contributing to this package?** 

- [ ] Yes, I can do this and open a PR for your review.
- [x] Possibly, but I'm not quite sure how to do this. I'd be happy to do a live coding session with someone to get this work implemented. 
- [ ] No, I'd prefer if someone else did this.  I don't have the time and/or don't know how to incorporate the changes necessary.

**Comment by fivetran-joemarkiewicz** [comment]
Thanks for opening this Issue @justinwagg!

I am currently going through and updating packages to be compatible with the latest dbt v0.20.0 release. I will prioritize this package and post back here once a new release is cut.

**Comment by justinwagg** [comment]
Thanks @fivetran-joemarkiewicz If I can help please let me know!

**Comment by fivetran-joemarkiewicz** [comment]
You caught me at the perfect time haha I was in between updates and just transitioned to Iterable right after. I just cut the `v0.2.0` release for iterable_source and will wait until it is up on the dbt hub to cut the new release of this package. Should be up in the next two hours!

**Comment by fivetran-joemarkiewicz** [comment]
@justinwagg I just cut the `v0.2.0` release for dbt_iterable! 🎉 It should be live on the dbt hub at the top of the hour.

Let me know if you have any other questions or requests. Please know that we are currently going through the process of updating our other packages. You can expect that all of our Fivetran dbt packages will have a version compatible with dbt 20 by the end of the week!
